name: ActualAccounts
options:
  minimumXcodeGenVersion: 2.39.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.actual.accounts
    DEVELOPMENT_TEAM: ""
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    SWIFT_VERSION: 5.10
packages: {}
targets:
  ActualAccounts:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App
      - path: Features
      - path: Networking
      - path: UI
      - path: Resources
        excludes:
          - README.md
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
    scheme:
      testTargets: []

